language: cpp

compiler:
  #- clang
  - gcc

before_install:
  # Install GYP
  - svn export http://gyp.googlecode.com/svn/trunk/ -r 1845 gyp
  - export PATH=$(pwd)/gyp:${PATH}

  # Install Ninja
  - wget https://github.com/martine/ninja/releases/download/v1.4.0/ninja-linux.zip
  - sudo unzip -d /usr/bin/ ninja-linux.zip
  
  # Install boost
  - sudo apt-get install libboost-test-dev
  - sudo apt-get install libsqlite3-dev

  # g++
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"

script:
  - ./build.sh
  - ./test.sh


git:
    depth: 2
